dependencies:
    -   python=3.7.3
    -   pip:
         - pandas
         - numpy
         - IPython
         - ipywidgets
         - jieba
         - nltk
         - wordcloud
         - matplotlib
         - imageio
         - bokeh
         - sklearn
         - gensim
         - scipy