dependencies:
    -   python=3.7.3
    -   pip:
         - pandas
         - numpy	
         - warnings
         - IPython
         - ipywidgets
         - jieba
         - nltk
         - wordcloud
         - matplotlib
         - imageio	